name: Release Notification

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version number'
        required: true
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update formula
        run: |
          VERSION=${{ github.event.inputs.version }}
          
          # Calculate SHA256
          URL="https://registry.npmjs.org/@aku11i/phantom/-/phantom-${VERSION}.tgz"
          SHA256=$(curl -sL "$URL" | sha256sum | cut -d' ' -f1)
          
          # Update formula
          sed -i "s|phantom-[0-9.]*\.tgz|phantom-${VERSION}.tgz|g" Formula/phantom.rb
          sed -i "s|sha256 \"[a-f0-9]*\"|sha256 \"$SHA256\"|g" Formula/phantom.rb

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Update phantom to ${{ github.event.inputs.version }}"
          title: "Update phantom to ${{ github.event.inputs.version }}"
          body: |
            ## 🚀 Phantom ${{ github.event.inputs.version }} has been released
            
            This PR updates the formula to support the new version of phantom.
            
            ### Changes
            - Update version to ${{ github.event.inputs.version }}
            - Update SHA256 checksum
            
            ### Testing
            ```bash
            brew install --build-from-source Formula/phantom.rb
            phantom version
            ```
          branch: update-phantom-${{ github.event.inputs.version }}
          delete-branch: true
          labels: |
            update
            automated